apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/y5u7j3p0/payment:latest
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: mongo-secret